
/****** Object:  Table [dbo].[MAS010_CODE_VALUES_TAB]    Script Date: 26.02.2013 10:09:41 *****
		MAS010 KODEVERDIER TABELL:
******/
/*CREATE TABLE Person( "+
	"PersonId int primary key NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),"+
	"Fornavn varchar(50) ,"+
	"Etternavn varchar(50) ,"+
	"Mail varchar(50) NOT NULL,"+
	"Hjemmeside varchar(50) ,"+
	"Mobil int ,"+
	"SistEndret timestamp )
	*/

--ta vekk dbo, klammer, sjekk lengde på feltnavn, datatyper


CREATE TABLE MAS010_CODE_VALUES_TAB(
	CLIENT_ID varchar()10) NOT NULL,
	COMPANY_ID varchar(10) NOT NULL,
	CODE_ID varchar(20) NOT NULL,
	CODE_VALUE varchar(10) NOT NULL,
	ACTIVE_SW char(2) for bit data NOT NULL DEFAULT (0),
	SHORT_DESCRIPTION varchar(10) NULL,
	DESCRIPTION varchar(40) NULL,
	SHORT_DESCRIPTION_RESOURCE_ID varchar(50) NULL,
	DESCRIPTION_RESOURCE_ID varchar(50) NULL,
	SORT_ORDER smallint NULL,
	CREATED_BY_USER varchar(10) NULL,
	CREATED_BY_PROGRAM varchar(10) NULL,
	CREATED_DATE timestamp NULL,
	ALTERED_BY_USER varchar(10) NULL,
	ALTERED_BY_PROGRAM varchar(10) NULL,
	ALTERED_DATE timestamp NULL,
	REVISION_NO smallint NULL DEFAULT (0),
 CONSTRAINT PK_MAS000_CODE_VALUES_TAB PRIMARY KEY CLUSTERED 
(
	CLIENT_ID ASC,
	COMPANY_ID ASC,
	CODE_ID ASC,
	CODE_VALUE ASC
)

--fjernet klammer: ok
--varchar: ok
--bit:feltnavn char (2) for bit data     ??
--smallint: ok, 2 byte of storage
--datetime: timestamp ??
--clustered primary key:??????????
--tatt vekk det siste, ON PRIMARY. dette er spesifikk for mssql db

--må ta vekk NULL fra i hvertfall varchar, dette feiler

GO



/****** Object:  Table [dbo].[MAS120_EMPLOYEE_TAB]    Script Date: 26.02.2013 10:14:16 *****
		MAS120 ANSATTDATA TABELL:
******/

CREATE TABLE MAS120_EMPLOYEE_TAB(
	CLIENT_ID varchar(10) NOT NULL,
	COMPANY_ID varchar(10) NOT NULL,
	EMPLOYEE_ID varchar(10) NOT NULL,
	FIRSTNAME varchar(50) NOT NULL,
	SURNAME varchar(50) NOT NULL,
	EMPLOYEE_TYPE_CODE varchar(10) NULL,
	INITIALS varchar(10) NULL,
	GENDER varchar(10) NULL,
	DATE_OF_BIRTH timestamp NULL,
	NATIONAL_IDENTITY_NO varchar(20) NULL,
	NATIONALITY varchar(10) NULL,
	PRE_GENERATE_HOURS_SW char(2) for bit data NOT NULL,
	REQ_HOURS_REG_SW char(2) for bit data NOT NULL,
	EMAIL_REMINDER_SW char(2) for bit data NOT NULL,
	EMAIL_WORK varchar(50) NULL,
	EMAIL_PRIVATE varchar(50) NULL,
	ELECTRONIC_PAYCHECK_CODE varchar(10) NULL,
	PHONE_NO_WORK varchar(20) NULL,
	PHONE_NO_PRIVATE varchar(20) NULL,
	PHONE_NO_MOBILE varchar(20) NULL,
	SUPERIOR_ID varchar(10) NULL,
	MATERIAL_STATUS_CODE varchar(10) NULL,
	NATIVE_COMPANY_SW char(2) for bit data NOT NULL,
	TRANSF_EMPL_PAYROLL_SW char(2) for bit data NOT NULL,
	COMPANY_CAR_SW char(2) for bit data NOT NULL,
	BANK_ACCOUNT_NO varchar(50) NULL,
	CREATED_BY_USER varchar(10) NULL,
	CREATED_BY_PROGRAM varchar(10) NULL,
	CREATED_DATE timestamp NULL,
	ALTERED_BY_USER varchar(10) NULL,
	ALTERED_BY_PROGRAM varchar(10) NULL,
	ALTERED_DATE timestamp NULL,
	REVISION_NO smallint NOT NULL,
	ABSENCE_MESSAGE_RECIPIENT_SW char(2) for bit data NOT NULL,
	PROJECT_RESPONSIBLE_SW char(2) for bit data NOT NULL,
	LAST_SETTLEMENT_DATE timestamp NULL,
 CONSTRAINT PK_MAS120_EMPLOYEE_TAB PRIMARY KEY CLUSTERED 
(
	CLIENT_ID ASC,
	COMPANY_ID ASC,
	EMPLOYEE_ID ASC
)

GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF__MAS000_EM__ADVAN__78B3EFCA]  DEFAULT (0) FOR [PRE_GENERATE_HOURS_SW]
GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF_MAS120_EMPLOYEE_TAB_REQ_HOURS_REG_SW]  DEFAULT (1) FOR [REQ_HOURS_REG_SW]
GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF__MAS000_EM__REMIN__79A81403]  DEFAULT (0) FOR [EMAIL_REMINDER_SW]
GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF_MAS120_EMPLOYEE_TAB_NATIVE_COMPANY_SW]  DEFAULT (0) FOR [NATIVE_COMPANY_SW]
GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF_MAS120_EMPLOYEE_TAB_TRANSF_EMPL_PAYROLL_SW]  DEFAULT (1) FOR [TRANSF_EMPL_PAYROLL_SW]
GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF_MAS120_EMPLOYEE_TAB_COMPANY_CAR_SW]  DEFAULT (0) FOR [COMPANY_CAR_SW]
GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF__MAS000_EM__REVIS__76CBA758]  DEFAULT (0) FOR [REVISION_NO]
GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF_MAS120_EMPLOYEE_TAB_ABSENCE_MESSAGE_RECIPIENT_SW]  DEFAULT (0) FOR [ABSENCE_MESSAGE_RECIPIENT_SW]
GO

ALTER TABLE [dbo].[MAS120_EMPLOYEE_TAB] ADD  CONSTRAINT [DF_MAS120_EMPLOYEE_TAB_PROJECT_RESPONSIBLE_SW]  DEFAULT (0) FOR [PROJECT_RESPONSIBLE_SW]
GO



/****** Object:  Table [dbo].[MAS121_EMPLOYEE_PERIODIC_TAB]    Script Date: 26.02.2013 10:15:33 
		MAS121 VARIABLE ANSATTDATA TABELL:
******/


CREATE TABLE MAS121_EMPLOYEE_PERIODIC_TAB](
	CLIENT_ID varchar](10) NOT NULL,
	COMPANY_ID varchar](10) NOT NULL,
	EMPLOYEE_ID varchar](10) NOT NULL,
	SERIAL_NO int NOT NULL,
	VALID_FROM_DATE [datetime] NOT NULL,
	VALID_TO_DATE [datetime] NULL,
	ADDRESS_LINE1 [varchar](50) NULL,
	ADDRESS_LINE2 [varchar](50) NULL,
	ZIP_CODE [varchar](10) NULL,
	COUNTRY_CODE [varchar](10) NULL,
	ADDRESS_ABROAD [varchar](50) NULL,
	PART_TIME_PERCENTAGE [decimal](5, 2) NULL,
	DISCIPLINE_CODE [varchar](10) NOT NULL,
	LOCATION_CODE varchar](10) NOT NULL,
	EMPLOYEE_STATUS_CODE [varchar](10) NOT NULL,
	TERMINATED_REASON [varchar](50) NULL,
	EMPLOYEE_CAT_CODE [varchar](10) NOT NULL,
	SALARY_CAT_CODE [varchar](10) NOT NULL,
	SALARY_TYPE_CODE [varchar](10) NOT NULL,
	PAYROLL_GROUP_CODE [varchar](10) NOT NULL,
	REGULAR_PROMAIN_ID [varchar](10) NULL,
	REGULAR_PROSUB_ID [varchar](10) NULL,
	TRADE_CODE varchar(10) NOT NULL,
	EMPLOYMENT_CODE [varchar](10) NULL,
	POSITION_TYPE_CODE [varchar](10) NOT NULL,
	OVERTIME_ENTITLED_SW [bit] NOT NULL,
	ORGANISATION_UNIT_ID [varchar](10) NOT NULL,
	SUPPLIER_ID varchar(10) NULL,
	INVOICE_PRICE_GRP_CODE [varchar](50) NOT NULL,
	CREATED_BY_USER [varchar](10) NULL,
	CREATED_BY_PROGRAM [varchar](10) NULL,
	CREATED_DATE [datetime] NOT NULL,
	ALTERED_BY_USER [varchar](10) NULL,
	ALTERED_BY_PROGRAM [varchar](10) NULL,
	ALTERED_DATE [datetime] NOT NULL,
	REVISION_NO [smallint] NOT NULL,
	LABOR_UNION_CODE [varchar](10) NULL,
	TERMINATED_REASON_CODE [varchar](10) NULL,
	SALARY_SCHEME [varchar](10) NULL,
 CONSTRAINT [PK_MAS121_EMPLOYEE_PERIODIC_TAB] PRIMARY KEY CLUSTERED 
(
	[CLIENT_ID] ASC,
	[COMPANY_ID] ASC,
	[EMPLOYEE_ID] ASC,
	[SERIAL_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MAS121_EMPLOYEE_PERIODIC_TAB] ADD  CONSTRAINT [DF_MAS121_EMPLOYEE_PERIODIC_TAB_PART_TIME_PERCENTAGE]  DEFAULT (0) FOR [PART_TIME_PERCENTAGE]
GO

ALTER TABLE [dbo].[MAS121_EMPLOYEE_PERIODIC_TAB] ADD  CONSTRAINT [DF_MAS121_EMPLOYEE_PERIODIC_TAB_OVERTIME_ENTITLED_SW]  DEFAULT (0) FOR [OVERTIME_ENTITLED_SW]
GO

ALTER TABLE [dbo].[MAS121_EMPLOYEE_PERIODIC_TAB] ADD  CONSTRAINT [DF_MAS121_EMPLOYEE_PERIODIC_TAB_CREATED_DATE]  DEFAULT (0) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[MAS121_EMPLOYEE_PERIODIC_TAB] ADD  CONSTRAINT [DF_MAS121_EMPLOYEE_PERIODIC_TAB_REVISION_NO]  DEFAULT (0) FOR [REVISION_NO]
GO


/****** Object:  Table [dbo].[MAS240_COST_UNIT_TAB]    Script Date: 26.02.2013 10:16:26 
		MAS240 KOSTNADSBÆRER TABELL
******/


CREATE TABLE [dbo].[MAS240_COST_UNIT_TAB](
	[CLIENT_ID] [varchar](10) NOT NULL,
	[COMPANY_ID] [varchar](10) NOT NULL,
	[COST_UNIT_ID] [varchar](15) NOT NULL,
	[PROMAIN_ID] [varchar](10) NOT NULL,
	[PROSUB_ID] [varchar](10) NOT NULL,
	[ACTIVITY_CODE] [varchar](20) NULL,
	[JOB_CODE] [varchar](10) NULL,
	[DESCRIPTION] [varchar](100) NULL,
	[VALID_FROM_DATE] [datetime] NULL,
	[VALID_TO_DATE] [datetime] NULL,
	[LOCATION_CODE] [varchar](10) NULL,
	[CUSTOMER_COST_UNIT] [varchar](50) NULL,
	[EXTERNAL_REFERENCE] [varchar](20) NULL,
	[CREATED_BY_USER] [varchar](10) NULL,
	[CREATED_BY_PROGRAM] [varchar](10) NULL,
	[CREATED_DATE] [datetime] NULL,
	[ALTERED_BY_USER] [varchar](10) NULL,
	[ALTERED_BY_PROGRAM] [varchar](10) NULL,
	[ALTERED_DATE] [datetime] NULL,
	[REVISION_NO] [smallint] NULL,
	[EXTERNAL_KEY1] [varchar](20) NULL,
	[EXTERNAL_KEY2] [varchar](20) NULL,
 CONSTRAINT [aaaaaMAS000_COST_UNIT_TAB_PK] PRIMARY KEY NONCLUSTERED 
(
	[COST_UNIT_ID] ASC,
	[COMPANY_ID] ASC,
	[CLIENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[HRS200_ROTATION_PLAN_TAB]    Script Date: 26.02.2013 10:17:34 
		HRS200 ROTASJON TABELL:
******/

CREATE TABLE [dbo].[HRS200_ROTATION_PLAN_TAB](
	[CLIENT_ID] [varchar](10) NOT NULL,
	[COMPANY_ID] [varchar](10) NOT NULL,
	[EMPLOYEE_ID] [varchar](10) NOT NULL,
	[ROTATION_ID] [varchar](10) NOT NULL,
	[PROMAIN_ID] [varchar](10) NOT NULL,
	[VALID_FROM_DATE] [datetime] NOT NULL,
	[VALID_TO_DATE] [datetime] NULL,
	[LOCATION_CODE] [varchar](10) NULL,
	[USE_REGULAR_PROJECT_SW] [bit] NOT NULL,
	[PROJECT_ROLE_CODE] [varchar](10) NULL,
	[CREATED_BY_USER] [varchar](10) NULL,
	[CREATED_BY_PROGRAM] [varchar](10) NULL,
	[CREATED_DATE] [datetime] NULL,
	[ALTERED_BY_USER] [varchar](10) NULL,
	[ALTERED_BY_PROGRAM] [varchar](10) NULL,
	[ALTERED_DATE] [datetime] NULL,
	[REVISION_NO] [smallint] NULL,
 CONSTRAINT [aaaaaHRS000_ROTATION_PLAN_TAB_PK] PRIMARY KEY NONCLUSTERED 
(
	[CLIENT_ID] ASC,
	[COMPANY_ID] ASC,
	[EMPLOYEE_ID] ASC,
	[ROTATION_ID] ASC,
	[VALID_FROM_DATE] ASC,
	[PROMAIN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[HRS200_ROTATION_PLAN_TAB] ADD  CONSTRAINT [DF_HRS200_ROTATION_PLAN_TAB_USER_REGULAR_PROJECT_SW]  DEFAULT (0) FOR [USE_REGULAR_PROJECT_SW]
GO

ALTER TABLE [dbo].[HRS200_ROTATION_PLAN_TAB] ADD  CONSTRAINT [DF__HRS000_RO__REVIS__182C9B23]  DEFAULT (0) FOR [REVISION_NO]
GO

/****** Object:  Table [dbo].[HRS100_HOURS_TYPE_TAB]    Script Date: 26.02.2013 10:18:31 
		HRS100 TIMETYPE TABELL
******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HRS100_HOURS_TYPE_TAB](
	[CLIENT_ID] [varchar](10) NOT NULL,
	[COMPANY_ID] [varchar](10) NOT NULL,
	[HOURS_TYPE_CODE] [varchar](10) NOT NULL,
	[HOURS_TYPE_GRP_CODE] [varchar](10) NULL,
	[DESCRIPTION] [varchar](50) NULL,
	[HOURS_MAIN_CAT_CODE] [varchar](10) NOT NULL,
	[HOURS_SUB_CAT_CODE] [varchar](10) NOT NULL,
	[PUBLIC_HOLIDAY_SW] [bit] NOT NULL,
	[COMPENSATED_IN_ROTATION_SW] [bit] NOT NULL,
	[ALLOW_LONG_TERM_ABSENCE_SW] [bit] NOT NULL,
	[AVAILABLE_FOR_REG_SW] [bit] NULL,
	[ALLOW_STATUS_LEAVE_SW] [bit] NULL,
	[INVOICE_UTILIZATION_CALC_SW] [bit] NOT NULL,
	[NORMAL_HOURS_SW] [bit] NOT NULL,
	[SICK_LEAVE_SW] [bit] NOT NULL,
	[OVERTIME_CALC_SW] [bit] NOT NULL,
	[MIN_PR_DAY] [decimal](5, 2) NULL,
	[MAX_PR_DAY] [decimal](5, 2) NULL,
	[FIXED_COST_UNIT_ID] [varchar](15) NULL,
	[VALID_FROM_DATE] [datetime] NULL,
	[VALID_TO_DATE] [datetime] NULL,
	[COMMENT] [varchar](200) NULL,
	[CREATED_BY_USER] [varchar](10) NULL,
	[CREATED_BY_PROGRAM] [varchar](10) NULL,
	[CREATED_DATE] [datetime] NULL,
	[ALTERED_BY_USER] [varchar](10) NULL,
	[ALTERED_BY_PROGRAM] [varchar](10) NULL,
	[ALTERED_DATE] [datetime] NULL,
	[REVISION_NO] [smallint] NULL,
	[AVG_CALC_MOB_CODE] [varchar](10) NOT NULL,
	[AVG_CALC_GRP_CODE] [varchar](10) NOT NULL,
	[MAX_PR_WEEK] [decimal](5, 2) NULL,
	[SPECIAL_ACCESS_ID] [varchar](50) NULL,
	[ALLOW_WAGE_TYPE_MAPPING_SW] [bit] NOT NULL,
	[REPORT_DESCRIPTION] [varchar](200) NULL,
	[OVERTIME_SW] [bit] NOT NULL,
 CONSTRAINT [PK_HRS100_HOURS_TYPE_TAB] PRIMARY KEY CLUSTERED 
(
	[CLIENT_ID] ASC,
	[COMPANY_ID] ASC,
	[HOURS_TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  CONSTRAINT [DF_HRS100_HOURS_TYPE_TAB_INVOICE_UTILIZATION_CALC_SW]  DEFAULT (0) FOR [INVOICE_UTILIZATION_CALC_SW]
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  CONSTRAINT [DF_HRS100_HOURS_TYPE_TAB_NORMAL_HOURS_SW]  DEFAULT (0) FOR [NORMAL_HOURS_SW]
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  CONSTRAINT [DF_HRS100_HOURS_TYPE_TAB_SICK_LEAVE_SW]  DEFAULT (0) FOR [SICK_LEAVE_SW]
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  CONSTRAINT [DF_HRS100_HOURS_TYPE_TAB_OVERTIME_CALC_SW]  DEFAULT (0) FOR [OVERTIME_CALC_SW]
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  CONSTRAINT [DF__HRS000_HO__REVIS__03317E3D]  DEFAULT (0) FOR [REVISION_NO]
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  CONSTRAINT [DF_HRS100_HOURS_TYPE_TAB_AVG_MOB_CODE]  DEFAULT ('NONE') FOR [AVG_CALC_MOB_CODE]
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  CONSTRAINT [DF_HRS100_HOURS_TYPE_TAB_AVG_CALC_GRP_CODE]  DEFAULT ('NONE') FOR [AVG_CALC_GRP_CODE]
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  DEFAULT ((1)) FOR [ALLOW_WAGE_TYPE_MAPPING_SW]
GO

ALTER TABLE [dbo].[HRS100_HOURS_TYPE_TAB] ADD  CONSTRAINT [DF__HRS100_HO__OVERT__35BF600F]  DEFAULT ((0)) FOR [OVERTIME_SW]
GO


/****** Object:  Table [dbo].[HRS500_HOURS_TAB]    Script Date: 26.02.2013 10:24:30 
		HRS500 TIME TABELL:
******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HRS500_HOURS_TAB](
	[CLIENT_ID] [varchar](10) NOT NULL,
	[COMPANY_ID] [varchar](10) NOT NULL,
	[RECORD_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_ID] [varchar](10) NOT NULL,
	[PROMAIN_ID] [varchar](10) NULL,
	[PROSUB_ID] [varchar](10) NULL,
	[ACTIVITY_CODE] [varchar](20) NULL,
	[JOB_CODE] [varchar](10) NULL,
	[COST_UNIT_ID] [varchar](15) NULL,
	[HOURS_TYPE_CODE] [varchar](10) NOT NULL,
	[HOURS_MAIN_CAT_CODE] [varchar](10) NOT NULL,
	[HOURS_SUB_CAT_CODE] [varchar](10) NOT NULL,
	[LOCATION_CODE] [varchar](10) NULL,
	[SHIFT_CODE] [varchar](10) NULL,
	[ROTATION_ID] [varchar](10) NULL,
	[ACCOUNTING_PERIOD_ID] [varchar](10) NULL,
	[WORK_MONTH] [varchar](7) NOT NULL,
	[WORK_DATE] [datetime] NOT NULL,
	[WORK_WEEK] [varchar](6) NOT NULL,
	[RECORD_TYPE_CODE] [varchar](10) NOT NULL,
	[CORR_REF_RECORD_ID] [int] NULL,
	[CORRECTED_SW] [bit] NOT NULL,
	[ROT_REF_RECORD_ID] [int] NULL,
	[SUBL_REF_RECORD_ID] [int] NULL,
	[IMP_REF_RECORD_ID] [int] NULL,
	[PAYMENT_CERTIFICATE_ID] [int] NULL,
	[HOURS] [decimal](7, 5) NOT NULL,
	[HOURS_RATE] [decimal](7, 2) NULL,
	[STATUS_CODE] [varchar](10) NOT NULL,
	[ATT_BY_USER_ID] [varchar](10) NULL,
	[ATT_DATE] [datetime] NULL,
	[SIGNED_DATE] [datetime] NULL,
	[SIGNED_BY_USER_ID] [varchar](10) NULL,
	[SENT_TO_USER_ID] [varchar](10) NULL,
	[TRANSF_PAYROLL_ID] [varchar](10) NULL,
	[TRANSF_FINANCE_ID] [varchar](10) NULL,
	[REPRICE_FINANCE_SW] [bit] NULL,
	[REPRICE_PAYROLL_SW] [bit] NULL,
	[CREATED_BY_USER] [varchar](10) NULL,
	[CREATED_BY_PROGRAM] [varchar](10) NULL,
	[CREATED_DATE] [datetime] NULL,
	[ALTERED_BY_USER] [varchar](10) NULL,
	[ALTERED_BY_PROGRAM] [varchar](10) NULL,
	[ALTERED_DATE] [datetime] NULL,
	[REVISION_NO] [smallint] NULL,
	[INVOICE_VOUCHER_ID] [int] NULL,
	[TRANSF_INDIRECT_COST_ID] [varchar](10) NULL,
	[PROJECT_ROLE_CODE] [varchar](10) NULL,
	[EXTRA_DIM1_CODE] [varchar](10) NULL,
	[EXTRA_DIM2_CODE] [varchar](10) NULL,
 CONSTRAINT [PK_HRS500_HOURS_TAB] PRIMARY KEY CLUSTERED 
(
	[RECORD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[HRS500_HOURS_TAB] ADD  CONSTRAINT [DF_HRS500_HOURS_TAB_RECORD_TYPE_CODE]  DEFAULT ('ORDINARY') FOR [RECORD_TYPE_CODE]
GO

ALTER TABLE [dbo].[HRS500_HOURS_TAB] ADD  CONSTRAINT [DF__HRS000_HO__HOURS__33D4B598]  DEFAULT (0) FOR [HOURS]
GO

ALTER TABLE [dbo].[HRS500_HOURS_TAB] ADD  CONSTRAINT [DF__HRS000_HO__REVIS__34C8D9D1]  DEFAULT (0) FOR [REVISION_NO]
GO