CREATE TABLE MAS010_CODE_VALUES_TAB(
	CLIENT_ID varchar()10) NOT NULL,
	COMPANY_ID varchar(10) NOT NULL,
	CODE_ID varchar(20) NOT NULL,
	CODE_VALUE varchar(10) NOT NULL,
	ACTIVE_SW char(2) for bit data NOT NULL DEFAULT (0),
	SHORT_DESCRIPTION varchar(10) NULL,
	DESCRIPTION varchar(40) NULL,
	SHORT_DESCRIPTION_RESOURCE_ID varchar(50) NULL,
	DESCRIPTION_RESOURCE_ID varchar(50) NULL,
	SORT_ORDER smallint NULL,
	CREATED_BY_USER varchar(10) NULL,
	CREATED_BY_PROGRAM varchar(10) NULL,
	CREATED_DATE timestamp NULL,
	ALTERED_BY_USER varchar(10) NULL,
	ALTERED_BY_PROGRAM varchar(10) NULL,
	ALTERED_DATE timestamp NULL,
	REVISION_NO smallint NULL DEFAULT (0),
 CONSTRAINT PK_MAS000_CODE_VALUES_TAB PRIMARY KEY CLUSTERED 
(
	CLIENT_ID ASC,
	COMPANY_ID ASC,
	CODE_ID ASC,
	CODE_VALUE ASC
)